//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ODEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int OgrtID { get; set; }
        public string OgrtAd { get; set; }
        public string OgrtSoyad { get; set; }
        public string OgrtYas { get; set; }
    }
}
